### ISSUE TITLE
How i execute this?

### ISSUE THREAD

**Issue by McParrot69** [KellenHurrey/UMCFixer#2]
i execute the .bat and gives me this error:

![Image](https://github.com/user-attachments/assets/ceb40a74-7ca7-4882-88af-62884a28dbc4)

**Comment by kelllllen** [comment]
Make sure "id("org.ajoberstar.grgit") version("3.1.1")" is commented out or removed in build.gradle. I have committed an update that did this, so make sure you are using the most recent version.

**Comment by McParrot69** [comment]
maybe idk how to use it, can u make a tutorial?

**Comment by kelllllen** [comment]
Are you just trying to use the mod? If so, just put it in your mods folder, along with immersive railroads, universal mod core, and GTNH Mixins. You can download it from the releases section on the right on the main page.

**Comment by McParrot69** [comment]
still crashing

[crash-2025-02-26_18.46.18-client.txt](https://github.com/user-attachments/files/18989866/crash-2025-02-26_18.46.18-client.txt)

**Comment by McParrot69** [comment]
crashing only when i go to other dimension
